version: '3.1'
services:

  php:
    image: php:7.3-apache
    volumes:
      - "/home/zanotta/docker/php:/var/www/html"
    ports:
      - "80:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - "/home/zanotta/docker/mysql:/var/lib/mysql"
    ports:
      - "3339:3306"
    environment:
      MYSQL_USER: zanotta
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 12345678

volumes:
  db_data: